# SL-ID: ISOS-SYNC-147.1
name: ISOS Master Auto-Sync

on:
  workflow_dispatch: # صرف بٹن دبانے پر چلے گا تاکہ ٹیسٹ ہو سکے
  schedule:
    - cron: '*/30 * * * *'

jobs:
  drive_sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync Files
        uses: jm-duarte/google-drive-sync-action@v1.0.1
        with:
          sk_file: ${{ secrets.GDRIVE_CREDENTIALS }}
          folder_id: '1Rl8h0nWh8MwCpOfRcxXibnJC7-sU1al1'
          destination: .

      - name: Push to GitHub
        run: |
          git config --global user.name "ISOS-BOT"
          git config --global user.email "isos@onlineservices.com"
          git add .
          git commit -m "Auto update" || exit 0
          git push origin main
