# ISOS Master Auto-Sync v12.0
name: ISOS Master Auto-Sync

on:
  schedule:
    - cron: '*/30 * * * *' # ہر آدھے گھنٹے بعد خودکار چیک
  workflow_dispatch: # مینوئل بٹن دبانے پر بھی کام کرے گا

jobs:
  drive_sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync from Google Drive
        uses: jm-duarte/google-drive-sync-action@v1.0.1
        with:
          sk_file: ${{ secrets.GDRIVE_CREDENTIALS }}
          folder_id: '1Rl8h0nWh8MwCpOfRcxXibnJC7-sU1al1' # آپ کا ڈرائیو فولڈر آئی ڈی
          destination: .
